[2024-05-20 21:39:06,213 INFO] * number of parameters: 120512513
[2024-05-20 21:39:06,213 INFO] Start training...
Traceback (most recent call last):
  File "D:\MDS-DR-master\src\train.py", line 155, in <module>
    train_ext_doc(args, device_id)
  File "D:\MDS-DR-master\src\train_extractive_doc.py", line 204, in train_ext
    train_single_ext(args, device_id)
  File "D:\MDS-DR-master\src\train_extractive_doc.py", line 254, in train_single_ext
    trainer.train(train_iter_fct, args.train_steps, valid_iter_fct, test_iter_fct)
  File "D:\MDS-DR-master\src\models\trainer_ext_doc.py", line 138, in train
    train_iter = train_iter_fct()
  File "D:\MDS-DR-master\src\train_extractive_doc.py", line 237, in train_iter_fct
    return data_loader.Dataloader(args, load_dataset(args, 'train', shuffle=True), args.batch_size, device,
  File "D:\MDS-DR-master\src\models\data_loader.py", line 139, in __init__
    self.cur_iter = self._next_dataset_iterator(datasets)
  File "D:\MDS-DR-master\src\models\data_loader.py", line 159, in _next_dataset_iterator
    self.cur_dataset = next(dataset_iter)
  File "D:\MDS-DR-master\src\models\data_loader.py", line 96, in load_dataset
    yield _lazy_dataset_loader(pt, corpus_type)
  File "D:\MDS-DR-master\src\models\data_loader.py", line 80, in _lazy_dataset_loader
    dataset = torch.load(pt_file)
  File "D:\anaconda\envs\SL\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\anaconda\envs\SL\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\anaconda\envs\SL\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '../bert_data2/xsum_doc_cls/train.pt'